name: university
description: "Welcome to University"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.10
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.26.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  very_good_analysis: ^5.1.0
  get_it: ^7.6.7
  url_launcher: ^6.2.5
  readmore: ^3.0.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  web: ^0.5.1
  image_picker_web: ^3.1.1



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: NunitoSans
  #     fonts:
  #       - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
        # - asset: assets/fonts/NunitoSans-Variable.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
