// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ5ezavi2vUdULjHmOghLlhszSOwFZko4',
    appId: '1:561504185381:web:e7b37cb429b91f50ef63cc',
    messagingSenderId: '561504185381',
    projectId: 'lalafo-app-1f168',
    authDomain: 'lalafo-app-1f168.firebaseapp.com',
    storageBucket: 'lalafo-app-1f168.appspot.com',
    measurementId: 'G-812XCF50JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMLTedQBtHUnnYUCpy3S6KAT0k39mNaQ',
    appId: '1:561504185381:android:4afb7a3149c5dadeef63cc',
    messagingSenderId: '561504185381',
    projectId: 'lalafo-app-1f168',
    storageBucket: 'lalafo-app-1f168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5cKxoZ1dlxAyaVXwp0M0lOpjzDJCcxcI',
    appId: '1:561504185381:ios:0bc2b27390fb31d0ef63cc',
    messagingSenderId: '561504185381',
    projectId: 'lalafo-app-1f168',
    storageBucket: 'lalafo-app-1f168.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5cKxoZ1dlxAyaVXwp0M0lOpjzDJCcxcI',
    appId: '1:561504185381:ios:0bc2b27390fb31d0ef63cc',
    messagingSenderId: '561504185381',
    projectId: 'lalafo-app-1f168',
    storageBucket: 'lalafo-app-1f168.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ5ezavi2vUdULjHmOghLlhszSOwFZko4',
    appId: '1:561504185381:web:e51ee94962f48170ef63cc',
    messagingSenderId: '561504185381',
    projectId: 'lalafo-app-1f168',
    authDomain: 'lalafo-app-1f168.firebaseapp.com',
    storageBucket: 'lalafo-app-1f168.appspot.com',
    measurementId: 'G-VCXXV2GDTX',
  );
}
